set(CTEST_CUSTOM_TESTS_IGNORE
	qtvector
	rand
	meta
	numext
	sizeof
	dynalloc
	nomalloc_1
	nomalloc_2
	nomalloc_3
	nomalloc_4
	nomalloc_5
	nomalloc_6
	nomalloc_7
	nomalloc_8
	first_aligned
	nullary_1
	nullary_2
	nullary_3
	nullary_4
	nullary_5
	nullary_6
	nullary_7
	nullary_8
	nullary_9
	nullary_10
	mixingtypes_1
	mixingtypes_2
	mixingtypes_3
	mixingtypes_4
	mixingtypes_5
	mixingtypes_6
	packetmath_1
	packetmath_2
	packetmath_3
	packetmath_4
	packetmath_5
	unalignedassert_1
	unalignedassert_2
	unalignedassert_3
	unalignedassert_4
	vectorization_logic_1
	vectorization_logic_2
	basicstuff_2
	basicstuff_1
	basicstuff_3
	basicstuff_4
	basicstuff_5
	basicstuff_6
	basicstuff_7
	constructor_1
	linearstructure_1
	linearstructure_2
	linearstructure_3
	linearstructure_4
	linearstructure_5
	linearstructure_6
	linearstructure_7
	linearstructure_8
	linearstructure_9
	linearstructure_10
	linearstructure_11
	integer_types_1
	integer_types_2
	integer_types_3
	integer_types_4
	integer_types_5
	integer_types_6
	integer_types_7
	integer_types_8
	integer_types_9
	unalignedcount
	exceptions
	redux_1
	redux_2
	redux_3
	redux_4
	redux_5
	redux_6
	redux_7
	redux_8
	visitor_1
	visitor_2
	visitor_3
	visitor_4
	visitor_5
	visitor_6
	visitor_7
	visitor_8
	visitor_9
	visitor_10
	block_1
	block_2
	block_3
	block_4
	block_5
	block_6
	block_8
	block_7
	corners_1
	corners_2
	corners_3
	corners_4
	corners_5
	symbolic_index_2
	symbolic_index_1
	indexed_view_2
	indexed_view_3
	indexed_view_1
	swap_1
	swap_2
	swap_3
	swap_4
	resize
	conservative_resize_1
	conservative_resize_2
	conservative_resize_3
	conservative_resize_4
	conservative_resize_5
	conservative_resize_6
	product_small_1
	product_small_2
	product_small_8
	product_small_3
	product_small_4
	product_small_5
	product_small_6
	product_small_11
	product_small_12
	product_small_13
	product_small_21
	product_small_22
	product_small_23
	product_small_31
	product_small_32
	product_small_33
	product_small_41
	product_small_42
	product_small_43
	product_small_7
	product_large_1
	product_large_2
	product_large_3
	product_large_4
	product_large_5
	product_large_6
	product_extra_1
	product_extra_2
	product_extra_3
	product_extra_4
	product_extra_5
	product_extra_6
	product_extra_7
	product_extra_8
	diagonalmatrices_1
	diagonalmatrices_2
	diagonalmatrices_3
	diagonalmatrices_4
	diagonalmatrices_5
	diagonalmatrices_6
	diagonalmatrices_7
	diagonalmatrices_8
	diagonalmatrices_9
	diagonalmatrices_10
	adjoint_1
	adjoint_2
	adjoint_3
	adjoint_4
	adjoint_5
	adjoint_6
	adjoint_8
	adjoint_9
	adjoint_10
	adjoint_11
	adjoint_12
	adjoint_7
	adjoint_13
	diagonal_1
	diagonal_2
	miscmatrices_1
	miscmatrices_2
	miscmatrices_3
	miscmatrices_4
	miscmatrices_5
	commainitializer
	smallvectors
	mapped_matrix_1
	mapped_matrix_2
	mapped_matrix_3
	mapped_matrix_4
	mapped_matrix_5
	mapped_matrix_11
	mapped_matrix_6
	mapped_matrix_7
	mapped_matrix_8
	mapped_matrix_9
	mapped_matrix_10
	mapstride_1
	mapstride_2
	mapstride_3
	mapstride_4
	mapstride_5
	mapstride_6
	mapstaticmethods_1
	mapstaticmethods_2
	mapstaticmethods_3
	mapstaticmethods_4
	mapstaticmethods_5
	mapstaticmethods_6
	mapstaticmethods_7
	mapstaticmethods_8
	array_1
	array_2
	array_3
	array_4
	array_5
	array_6
	array_for_matrix_1
	array_for_matrix_2
	array_for_matrix_3
	array_for_matrix_4
	array_for_matrix_5
	array_for_matrix_6
	array_for_matrix_7
	array_for_matrix_8
	array_replicate_1
	array_replicate_2
	array_replicate_3
	array_replicate_4
	array_replicate_5
	array_replicate_6
	array_reverse_1
	array_reverse_2
	array_reverse_3
	array_reverse_4
	array_reverse_5
	array_reverse_6
	array_reverse_7
	array_reverse_8
	array_reverse_9
	ref_1
	ref_2
	ref_3
	ref_4
	ref_5
	ref_6
	ref_7
	is_same_dense
	triangular_1
	triangular_2
	triangular_3
	triangular_4
	triangular_5
	triangular_6
	triangular_7
	triangular_8
	triangular_9
	selfadjoint_1
	selfadjoint_2
	selfadjoint_3
	selfadjoint_4
	selfadjoint_5
	product_selfadjoint_1
	product_selfadjoint_2
	product_selfadjoint_3
	product_selfadjoint_4
	product_selfadjoint_5
	product_selfadjoint_6
	product_selfadjoint_7
	product_symm_1
	product_symm_2
	product_symm_3
	product_symm_4
	product_symm_5
	product_symm_6
	product_symm_7
	product_symm_8
	product_syrk_1
	product_syrk_2
	product_syrk_3
	product_syrk_4
	product_trmv_1
	product_trmv_2
	product_trmv_3
	product_trmv_4
	product_trmv_5
	product_trmv_6
	product_trmm_1
	product_trmm_11
	product_trmm_111
	product_trmm_21
	product_trmm_121
	product_trmm_31
	product_trmm_131
	product_trmm_12
	product_trmm_112
	product_trmm_22
	product_trmm_122
	product_trmm_32
	product_trmm_132
	product_trmm_13
	product_trmm_113
	product_trmm_23
	product_trmm_123
	product_trmm_33
	product_trmm_133
	product_trmm_14
	product_trmm_114
	product_trmm_24
	product_trmm_124
	product_trmm_34
	product_trmm_134
	product_trsolve_1
	product_trsolve_2
	product_trsolve_3
	product_trsolve_4
	product_trsolve_5
	product_trsolve_6
	product_trsolve_7
	product_trsolve_8
	product_trsolve_9
	product_trsolve_10
	product_trsolve_11
	product_trsolve_12
	product_trsolve_13
	product_trsolve_14
	product_mmtr_1
	product_mmtr_2
	product_mmtr_3
	product_mmtr_4
	product_notemporary_1
	product_notemporary_2
	product_notemporary_3
	product_notemporary_4
	stable_norm_1
	stable_norm_2
	stable_norm_3
	stable_norm_4
	stable_norm_5
	permutationmatrices_1
	permutationmatrices_2
	permutationmatrices_3
	permutationmatrices_4
	permutationmatrices_5
	permutationmatrices_6
	permutationmatrices_7
	bandmatrix
	cholesky_1
	cholesky_3
	cholesky_4
	cholesky_5
	cholesky_2
	cholesky_6
	cholesky_7
	cholesky_8
	cholesky_9
	lu_1
	lu_2
	lu_3
	lu_4
	lu_5
	lu_6
	lu_7
	lu_9
	determinant_1
	determinant_2
	determinant_3
	determinant_4
	determinant_5
	determinant_6
	inverse_5
	inverse_6
	inverse_1
	inverse_2
	inverse_3
	inverse_4
	inverse_7
	qr_1
	qr_2
	qr_3
	qr_4
	qr_5
	qr_11
	qr_6
	qr_7
	qr_8
	qr_9
	qr_10
	qr_12
	qr_colpivoting_1
	qr_colpivoting_2
	qr_colpivoting_3
	qr_colpivoting_4
	qr_colpivoting_5
	qr_colpivoting_6
	qr_colpivoting_7
	qr_colpivoting_8
	qr_colpivoting_9
	qr_fullpivoting_1
	qr_fullpivoting_2
	qr_fullpivoting_3
	qr_fullpivoting_4
	qr_fullpivoting_5
	qr_fullpivoting_6
	qr_fullpivoting_7
	upperbidiagonalization_1
	upperbidiagonalization_2
	upperbidiagonalization_3
	upperbidiagonalization_4
	upperbidiagonalization_5
	upperbidiagonalization_6
	upperbidiagonalization_7
	hessenberg_1
	hessenberg_2
	hessenberg_3
	hessenberg_4
	hessenberg_5
	hessenberg_6
	schur_real_1
	schur_real_2
	schur_real_3
	schur_real_4
	schur_real_5
	schur_complex_1
	schur_complex_2
	schur_complex_3
	schur_complex_4
	schur_complex_5
	eigensolver_selfadjoint_1
	eigensolver_selfadjoint_12
	eigensolver_selfadjoint_13
	eigensolver_selfadjoint_2
	eigensolver_selfadjoint_3
	eigensolver_selfadjoint_4
	eigensolver_selfadjoint_5
	eigensolver_selfadjoint_9
	eigensolver_selfadjoint_6
	eigensolver_selfadjoint_7
	eigensolver_selfadjoint_8
	eigensolver_generic_1
	eigensolver_generic_2
	eigensolver_generic_3
	eigensolver_generic_4
	eigensolver_generic_5
	eigensolver_complex_1
	eigensolver_complex_2
	eigensolver_complex_3
	eigensolver_complex_4
	eigensolver_complex_5
	real_qz_1
	real_qz_2
	real_qz_3
	real_qz_4
	eigensolver_generalized_real_1
	eigensolver_generalized_real_2
	eigensolver_generalized_real_3
	eigensolver_generalized_real_4
	jacobi_1
	jacobi_2
	jacobi_3
	jacobi_4
	jacobi_5
	jacobi_6
	jacobisvd_3
	jacobisvd_4
	jacobisvd_7
	jacobisvd_8
	jacobisvd_11
	jacobisvd_12
	jacobisvd_5
	jacobisvd_6
	jacobisvd_10
	jacobisvd_13
	jacobisvd_1
	jacobisvd_9
	jacobisvd_2
	bdcsvd_3
	bdcsvd_4
	bdcsvd_7
	bdcsvd_8
	bdcsvd_101
	bdcsvd_102
	bdcsvd_5
	bdcsvd_6
	bdcsvd_10
	bdcsvd_1
	bdcsvd_9
	bdcsvd_2
	householder_1
	householder_2
	householder_3
	householder_4
	householder_5
	householder_6
	householder_7
	householder_8
	geo_orthomethods_1
	geo_orthomethods_2
	geo_orthomethods_4
	geo_orthomethods_3
	geo_orthomethods_5
	geo_orthomethods_6
	geo_quaternion_1
	geo_quaternion_2
	geo_quaternion_3
	geo_quaternion_4
	geo_quaternion_5
	geo_quaternion_6
	geo_eulerangles_1
	geo_eulerangles_2
	geo_parametrizedline_1
	geo_parametrizedline_2
	geo_parametrizedline_3
	geo_parametrizedline_4
	geo_alignedbox_1
	geo_alignedbox_2
	geo_alignedbox_3
	geo_alignedbox_4
	geo_alignedbox_5
	geo_alignedbox_6
	geo_alignedbox_7
	geo_alignedbox_8
	geo_alignedbox_9
	geo_alignedbox_10
	geo_alignedbox_11
	geo_alignedbox_14
	geo_alignedbox_12
	geo_alignedbox_13
	geo_hyperplane_1
	geo_hyperplane_2
	geo_hyperplane_3
	geo_hyperplane_4
	geo_hyperplane_5
	geo_transformations_1
	geo_transformations_2
	geo_transformations_3
	geo_transformations_4
	geo_transformations_5
	geo_transformations_6
	geo_transformations_7
	geo_transformations_8
	geo_homogeneous_1
	geo_homogeneous_2
	geo_homogeneous_3
	stdvector_1
	stdvector_2
	stdvector_3
	stdvector_4
	stdvector_5
	stdvector_overload_1
	stdvector_overload_2
	stdvector_overload_3
	stdvector_overload_4
	stdvector_overload_5
	stdlist_1
	stdlist_2
	stdlist_3
	stdlist_4
	stdlist_5
	stdlist_overload_1
	stdlist_overload_2
	stdlist_overload_3
	stdlist_overload_4
	stdlist_overload_5
	stddeque_1
	stddeque_2
	stddeque_3
	stddeque_4
	stddeque_5
	stddeque_overload_1
	stddeque_overload_2
	stddeque_overload_3
	stddeque_overload_4
	stddeque_overload_5
	sparse_basic_1
	sparse_basic_2
	sparse_basic_5
	sparse_basic_6
	sparse_basic_3
	sparse_basic_4
	sparse_basic_7
	sparse_block_1
	sparse_block_2
	sparse_block_3
	sparse_block_4
	sparse_vector_1
	sparse_vector_2
	sparse_product_1
	sparse_product_2
	sparse_product_3
	sparse_product_4
	sparse_product_5
	sparse_ref_1
	sparse_ref_2
	sparse_ref_3
	sparse_solvers_1
	sparse_solvers_2
	sparse_permutations_1
	sparse_permutations_2
	simplicial_cholesky_1
	simplicial_cholesky_2
	simplicial_cholesky_3
	conjugate_gradient_1
	conjugate_gradient_2
	conjugate_gradient_3
	incomplete_cholesky_1
	incomplete_cholesky_2
	incomplete_cholesky_3
	bicgstab_1
	bicgstab_2
	bicgstab_3
	lscg_1
	lscg_2
	sparselu_1
	sparselu_2
	sparselu_3
	sparselu_4
	sparseqr_1
	sparseqr_2
	umeyama_1
	umeyama_2
	umeyama_3
	umeyama_4
	umeyama_5
	umeyama_6
	umeyama_7
	umeyama_8
	nesting_ops_1
	nesting_ops_2
	nesting_ops_3
	nesting_ops_4
	zerosized
	dontalign_1
	dontalign_2
	dontalign_3
	dontalign_4
	dontalign_5
	dontalign_6
	dontalign_7
	dontalign_8
	evaluators
	sizeoverflow
	prec_inverse_4x4_1
	prec_inverse_4x4_2
	prec_inverse_4x4_3
	vectorwiseop_1
	vectorwiseop_2
	vectorwiseop_3
	vectorwiseop_4
	vectorwiseop_5
	vectorwiseop_6
	vectorwiseop_7
	special_numbers_1
	rvalue_types_1
	rvalue_types_2
	dense_storage
	ctorleak
	mpl2only
	inplace_decomposition_1
	inplace_decomposition_2
	inplace_decomposition_3
	inplace_decomposition_4
	inplace_decomposition_5
	inplace_decomposition_6
	inplace_decomposition_7
	inplace_decomposition_8
	half_float
	array_of_string
	fastmath
	umfpack_support_1
	umfpack_support_2
	superlu_support_1
	superlu_support_2
	cholmod_support_11
	cholmod_support_12
	cholmod_support_13
	cholmod_support_14
	cholmod_support_21
	cholmod_support_22
	cholmod_support_23
	cholmod_support_24
	spqr_support_1
	spqr_support_2
	metis_support_1
	boostmultiprec_1
	boostmultiprec_2
	boostmultiprec_3
	boostmultiprec_4
	boostmultiprec_5
	boostmultiprec_6
	boostmultiprec_7
	boostmultiprec_8
	boostmultiprec_9
	boostmultiprec_10
	failtests
	sblat1
	sblat2
	sblat3
	dblat1
	dblat2
	dblat3
	cblat1
	cblat2
	cblat3
	zblat1
	zblat2
	zblat3
	forward_adolc
	NonLinearOptimization
	NumericalDiff
	autodiff_scalar_1
	autodiff_scalar_2
	autodiff_scalar_3
	autodiff_scalar_4
	autodiff_scalar_5
	autodiff_1
	autodiff_2
	autodiff_3
	autodiff_4
	BVH_1
	BVH_2
	BVH_3
	matrix_exponential_2
	matrix_exponential_1
	matrix_exponential_8
	matrix_exponential_6
	matrix_exponential_5
	matrix_exponential_7
	matrix_exponential_3
	matrix_exponential_4
	matrix_exponential_9
	matrix_function_1
	matrix_function_2
	matrix_function_3
	matrix_function_4
	matrix_function_5
	matrix_function_6
	matrix_function_7
	matrix_power_2
	matrix_power_1
	matrix_power_9
	matrix_power_10
	matrix_power_11
	matrix_power_12
	matrix_power_7
	matrix_power_3
	matrix_power_4
	matrix_power_5
	matrix_power_8
	matrix_power_6
	matrix_square_root_1
	matrix_square_root_2
	matrix_square_root_3
	matrix_square_root_4
	matrix_square_root_5
	alignedvector3
	FFT
	EulerAngles_1
	EulerAngles_2
	EulerAngles_3
	EulerAngles_4
	mpreal_support
	sparse_extra_1
	sparse_extra_2
	sparse_extra_3
	sparse_extra_4
	FFTW
	polynomialsolver_1
	polynomialsolver_2
	polynomialsolver_3
	polynomialsolver_4
	polynomialsolver_5
	polynomialsolver_6
	polynomialsolver_7
	polynomialsolver_8
	polynomialsolver_9
	polynomialsolver_10
	polynomialsolver_11
	polynomialsolver_12
	polynomialutils_2
	polynomialutils_3
	polynomialutils_4
	polynomialutils_5
	polynomialutils_6
	polynomialutils_7
	polynomialutils_8
	polynomialutils_9
	splines
	gmres_1
	gmres_2
	minres_1
	minres_2
	levenberg_marquardt
	kronecker_product_1
	kronecker_product_2
	special_functions_1
	special_functions_2
	cxx11_tensor_dimension
	cxx11_tensor_map
	cxx11_tensor_assign
	cxx11_tensor_comparisons
	cxx11_tensor_forced_eval
	cxx11_tensor_math
	cxx11_tensor_const
	cxx11_tensor_intdiv_1
	cxx11_tensor_intdiv_2
	cxx11_tensor_intdiv_3
	cxx11_tensor_intdiv_4
	cxx11_tensor_intdiv_5
	cxx11_tensor_intdiv_6
	cxx11_tensor_intdiv_7
	cxx11_tensor_casts
	cxx11_tensor_empty
	cxx11_tensor_sugar
	cxx11_tensor_roundings
	cxx11_tensor_layout_swap
	cxx11_tensor_io
	cxx11_tensor_uint128_1
	cxx11_tensor_uint128_2
	cxx11_tensor_uint128_3
	cxx11_tensor_uint128_4
	cxx11_tensor_uint128_5
	cxx11_tensor_uint128_6
	catch_tests
	type_alias
	mixingtypes_7
	packetmath_6
	reshape
	array_cwise_1
	array_cwise_2
	array_cwise_3
	array_cwise_4
	array_cwise_5
	array_cwise_6
	triangular_100
	stable_norm_6
	inverse_8
	qr_fullpivoting_8
	geo_transformations_9
	sparse_block_5
	nestbyvalue
	num_dimensions
	stl_iterators_1
	failtest_sanity_check_ok
	failtest_sanity_check_ko
	block_nonconst_ctor_on_const_xpr_0_ok
	block_nonconst_ctor_on_const_xpr_0_ko
	block_nonconst_ctor_on_const_xpr_1_ok
	block_nonconst_ctor_on_const_xpr_1_ko
	block_nonconst_ctor_on_const_xpr_2_ok
	block_nonconst_ctor_on_const_xpr_2_ko
	transpose_nonconst_ctor_on_const_xpr_ok
	transpose_nonconst_ctor_on_const_xpr_ko
	diagonal_nonconst_ctor_on_const_xpr_ok
	diagonal_nonconst_ctor_on_const_xpr_ko
	cwiseunaryview_nonconst_ctor_on_const_xpr_ok
	cwiseunaryview_nonconst_ctor_on_const_xpr_ko
	triangularview_nonconst_ctor_on_const_xpr_ok
	triangularview_nonconst_ctor_on_const_xpr_ko
	selfadjointview_nonconst_ctor_on_const_xpr_ok
	selfadjointview_nonconst_ctor_on_const_xpr_ko
	const_qualified_block_method_retval_0_ok
	const_qualified_block_method_retval_0_ko
	const_qualified_block_method_retval_1_ok
	const_qualified_block_method_retval_1_ko
	const_qualified_transpose_method_retval_ok
	const_qualified_transpose_method_retval_ko
	const_qualified_diagonal_method_retval_ok
	const_qualified_diagonal_method_retval_ko
	map_nonconst_ctor_on_const_ptr_0_ok
	map_nonconst_ctor_on_const_ptr_0_ko
	map_nonconst_ctor_on_const_ptr_1_ok
	map_nonconst_ctor_on_const_ptr_1_ko
	map_nonconst_ctor_on_const_ptr_2_ok
	map_nonconst_ctor_on_const_ptr_2_ko
	map_nonconst_ctor_on_const_ptr_3_ok
	map_nonconst_ctor_on_const_ptr_3_ko
	map_nonconst_ctor_on_const_ptr_4_ok
	map_nonconst_ctor_on_const_ptr_4_ko
	map_on_const_type_actually_const_0_ok
	map_on_const_type_actually_const_0_ko
	map_on_const_type_actually_const_1_ok
	map_on_const_type_actually_const_1_ko
	block_on_const_type_actually_const_0_ok
	block_on_const_type_actually_const_0_ko
	block_on_const_type_actually_const_1_ok
	block_on_const_type_actually_const_1_ko
	transpose_on_const_type_actually_const_ok
	transpose_on_const_type_actually_const_ko
	diagonal_on_const_type_actually_const_ok
	diagonal_on_const_type_actually_const_ko
	cwiseunaryview_on_const_type_actually_const_ok
	cwiseunaryview_on_const_type_actually_const_ko
	triangularview_on_const_type_actually_const_ok
	triangularview_on_const_type_actually_const_ko
	selfadjointview_on_const_type_actually_const_ok
	selfadjointview_on_const_type_actually_const_ko
	ref_1_ok
	ref_1_ko
	ref_2_ok
	ref_2_ko
	ref_3_ok
	ref_3_ko
	ref_4_ok
	ref_4_ko
	ref_5_ok
	ref_5_ko
	swap_1_ok
	swap_1_ko
	swap_2_ok
	swap_2_ko
	ternary_1_ok
	ternary_1_ko
	ternary_2_ok
	ternary_2_ko
	sparse_ref_1_ok
	sparse_ref_1_ko
	sparse_ref_2_ok
	sparse_ref_2_ko
	sparse_ref_3_ok
	sparse_ref_3_ko
	sparse_ref_4_ok
	sparse_ref_4_ko
	sparse_ref_5_ok
	sparse_ref_5_ko
	sparse_storage_mismatch_ok
	sparse_storage_mismatch_ko
	partialpivlu_int_ok
	partialpivlu_int_ko
	fullpivlu_int_ok
	fullpivlu_int_ko
	llt_int_ok
	llt_int_ko
	ldlt_int_ok
	ldlt_int_ko
	qr_int_ok
	qr_int_ko
	colpivqr_int_ok
	colpivqr_int_ko
	fullpivqr_int_ok
	fullpivqr_int_ko
	jacobisvd_int_ok
	jacobisvd_int_ko
	bdcsvd_int_ok
	bdcsvd_int_ko
	eigensolver_int_ok
	eigensolver_int_ko
	eigensolver_cplx_ok
	eigensolver_cplx_ko
	autodiff_5
	dgmres_1
	dgmres_2
	cxx11_tensor_block_access
	cxx11_maxsizevector
    umfpack_support_3
    umfpack_support_4
    klu_support_1
    klu_support_2
    boostmultiprec_11
)
